# Generated by Django 5.2.12 on 2026-04-21 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.RemoveIndex(
            model_name='allocation',
            name='essa_alloca_allocat_1f85b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='allocation',
            name='essa_alloca_employe_1431aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='bus',
            name='essa_bus_bus_num_fca884_idx',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['bus_location'], name='essa_bus_bus_loc_38b2ae_idx'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='incoming_time',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='essa.incomingtime'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='allocation',
            name='outgoing_time',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='essa.outgoingtime'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('employee', 'allocation_date', 'incoming_time', 'outgoing_time')},
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['allocation_date', 'incoming_time', 'outgoing_time'], name='essa_alloca_allocat_e1d454_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['employee', 'allocation_date', 'incoming_time', 'outgoing_time'], name='essa_alloca_employe_dacf38_idx'),
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='allocation_time',
        ),
    ]
