# Generated by Django 5.2.12 on 2026-04-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
    ]
