# Generated by Django 5.2.12 on 2026-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0002_alter_bus_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bus',
            name='essa_bus_bus_num_fca884_idx',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['bus_location'], name='essa_bus_bus_loc_38b2ae_idx'),
        ),
    ]
