# Generated by Django 5.2.12 on 2026-04-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0002_incomingtime_outgoingtime_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='incoming_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='outgoing_time',
            field=models.CharField(max_length=5),
        ),
        migrations.RenameIndex(
            model_name='allocation',
            new_name='essa_alloca_allocat_4bf403_idx',
            old_name='essa_alloca_allocat_e1d454_idx',
        ),
        migrations.RenameIndex(
            model_name='allocation',
            new_name='essa_alloca_employe_26b753_idx',
            old_name='essa_alloca_employe_dacf38_idx',
        ),
        migrations.DeleteModel(
            name='IncomingTime',
        ),
        migrations.DeleteModel(
            name='OutgoingTime',
        ),
    ]
