# Generated by Django 5.2.12 on 2026-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0003_alter_allocation_incoming_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='remaining_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
