# Generated by Django 5.2.12 on 2026-05-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0004_bus_remaining_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('incoming_time', models.CharField(max_length=5)),
                ('outgoing_time', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_traces', to='essa.bus')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_traces', to='essa.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['allocation_date', 'incoming_time', 'outgoing_time'], name='essa_alloca_allocat_6c6847_idx'), models.Index(fields=['employee', 'allocation_date', 'incoming_time', 'outgoing_time'], name='essa_alloca_employe_6cccc4_idx')],
            },
        ),
    ]
