# Generated by Django 5.2.12 on 2026-05-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0005_allocationtrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationtrace',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='essa.bus'),
        ),
        migrations.AlterField(
            model_name='allocationtrace',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='essa.employee'),
        ),
        migrations.AlterField(
            model_name='allocationtrace',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='allocationtrace',
            unique_together={('employee', 'allocation_date', 'incoming_time', 'outgoing_time')},
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
