# Generated by Django 5.2.12 on 2026-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essa', '0006_alter_allocationtrace_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='BU',
            field=models.CharField(choices=[('ERTI', 'ERTI'), ('ESPI', 'ESPI'), ('CREOTEC', 'CREOTEC'), ('CANTEEN', 'CANTEEN'), ('SECURITY', 'SECURITY'), ('TOPSEARCH', 'TOPSEARCH'), ('IT', 'IT'), ('INTERNAL_AUDITOR', 'INTERNAL_AUDITOR'), ('CORPORATE_AFFAIRS', 'CORPORATE_AFFAIRS'), ('HRT', 'HRT')], default=3, max_length=20),
            preserve_default=False,
        ),
    ]
